---
title: "Hunting experience and prey variability jointly shape individual foraging specialisation in a predator-prey videogame"
output: 
  word_document:
    reference_docx: Chapter3-styles.docx
bibliography: references.bib
csl: e-letters.csl
---


\newpage
# Abstract {.unnumbered}

Keywords: foraging behaviour, individual specialization, experience, learning, prey predictability, online videogames


\newpage
# Introduction {.unnumbered}

Individual variation in predator foraging behaviour is increasingly recognized as a major driver of trophic interactions and community dynamics [@limaPuttingPredatorsBack2002;@schreiberCommunityEffectsPhenotypic2011;@pettorelliChapterTwoIndividual2015;@Michalko.Pekar2016]. Indeed, predator populations are often composed of assemblages of individuals specializing in different foraging strategies or resources irrespective of sexual, morphological, or age-related differences [@estesIndividualVariationPrey2003;@tinkerFoodLimitationLeads2008;@kernaleguenDeterminantsIndividualForaging2015;@Phillips.etal2017] (FIND SOME TERRESTRIAL ANIMAL REFS). A growing body of evidence suggests that ecological interactions, such as predator-prey interactions, can be major drivers of such individual foraging specialization [@araujoEcologicalCausesIndividual2011;@toscanoPersonalityForagingBehavior2016]. When hunting, predators often use hunting techniques that are fine-tuned to the type of prey that they encounter [@Davoren.etal2003;@estesIndividualVariationPrey2003;@Woo.etal2008;@courbinShorttermPreyField2018], and their capacity to use them effectively is contingent on periods of extensive practice (i.e. expertise). While the development of hunting expertise may be essential to maintain foraging success, we have have limited evidence for its role in predator foraging specialization, and the ecological/fitness consequences of such among individual behavioural differences for predator-prey interactions.

The integration of individual behavioral variation into studies of predator-prey interactions has been championned for some time, and a series of empirical papers have revelealed important insights on its consequences for functional responses, habitat use, and prey choice. However, a recurring challenge impeding empirical studies of predator-prey behavioral interactions is the difficulty of collecting data simultaneously on both the predator and prey. We have recently demonstrated that using an online predator-prey videogame can help uncover subtle details about the mechanisms shaping these behavioral interactions [@FraserFranco].


*ici, mettre le paragraphe sur la variation individuelle, et ensuite expliquer ce qu'on cherche à comprendre dans la littérature écologique comportementale*



The development of foraging strategies is crucial for young predators to reach adulthood and survive [@Phillips.etal2017;@heithausFeedingStrategiesTactics2018]. Theory predicts that foraging specialization may emerge via learning, limitations in memorizing multiple complex hunting skills, and expertise [@Tinker.etal2009;@Dukas2019]. [Dukas @Dukas2019] defines expertise as the characteristics, skills, and knowledge allowing individuals with extensive experience to outperform novices on complex tasks. This body of work suggests that the development of expertise is an optimizing process that promotes foraging specialization. Empirical studies show that expertise allows predators to optimize the efficiency (e.g. search and handling times, return rates) of their foraging tactics potentially via associative images or reliance on prey and environmental cues [@edwardsRoleExperienceDevelopment1994;@morseEffectExperienceHunting2000;@reidLearningHuntRole2010;@wilson-rankinLevelExperienceModulates2015]. Such optimization may thus reinforce the use of the same tactic (i.e. specialization) if its success is constant each time a prey is encountered. It may also be costly to attempt different hunting tactics when prey are scarce or highly unpredictable [@estesIndividualVariationPrey2003;@Mery.Burns2010]. An alternative mechanism is that expertise may offset the costs/risks of switching foraging tactics as individuals gain experience and information on their prey or their environment, leading to increased individual foraging flexibility [@Ishii.Shimada2010;@Mery.Burns2010;@Snell-Rood2013]. In this case, switching between foraging tactics would be advantageous when resources are variable, as behavioural flexibility is often key for survival in novel environments [reviewed in @Snell-Rood2013] (FIND OTHER REFS TO SUPPORT THIS MAYBE DAN SOL?). 

*un autre truc que je pourrais parler est le fait que si on assume que les individus deviennent meilleurs avec l'expertise (Dukas), on voit pourtant dans les études marines que les individus de groupes d'âges variés performent souvent de manière similaire. Ça amènerait bien l'autre paragraphe pour montrer que les interactions écologiques ont un rôle clé!!*

*ou juste dire que pour comprendre le role de l'expertise, il faut s'attarder à l'étudier avec la specialisation et voir les consequences pour la fitness ou issue des interactions predateur proie. ca introduit mieux je crois. dire genre que une théorie prédit que spécialisation est avantage quand proies peu variable, et ensuite ça lie bien l'hypothèse de variabilité que je décris en bas*


A number of long-term studies observed that generalist and specialist individuals can achieve similar fitness [sources: à partir de Woo]. An emerging explanation is that temporal fluctuations in the predictability of resources (abundance, availability, behaviour) may favor one or the other strategy depending on time scales [sources : Woo, Phillips, Ceia, etc, Courbin, Chang]. The resource-predictability hypothesis advances that when resources are predictable, particularly on short time-scales, individual specialists should benefit from higher fitness returns. The rationale is that individuals should have higher prey delivery rates when they repeatedly employ the same foraging technique, as it is easier to assess prey predictability over shorter time-scales. In contrast, individual generalists should be advantaged over longer time scales, as resource parameters are expected to fluctuate. [revoir ceia et ramos pour les sources]
*ce qu'il manque, c'est qu'on a aucune idée comment des différences individuelles de variabilité environnementale se traduisent par des différences de stratégies*

sources générales sur heterogeneité[@Weimerskirch2007;@ceiaIndividualSpecializationForaging2015;@Phillips.etal2017;@Patrick.etal2021]. 

 *Difficile de mesurer à travers le temps blabla. J'introduis ensuite le jeu vidéo* *vidfeogames offer a good alternative to lab studies because proche de wild = observational*
*(idéee: par contre, décomposer l'âge de l'expérience est difficile, et particulièrement chez des espèces sur le terrain puisque ça peut impliquer des techniques invasives)*

Here, we collected individual behavioural data from players in *Dead by Daylight* to investigate how hunting experience and the behavioural variation in prey encountered shaped predator foraging specialization. This enabled us to have a high degree of precision on the interaction as both the behaviour of the predator and the four prey were measured simultaneously in each trial. First, we hypothesize that individual predator behaviour will change with hunting experience. If experience reduces the costs of switching between hunting tactics, then predators should become more flexible through time. Alternatively, if experience enables the refinement of the hunting tactics, then individuals may instead specialize through time. Second, we hypothesize that prey behaviour will shape the developmental trajectories of the predator hunting tactics. Whether predators specialize or not with experience may depend on the behaviour of their prey, for instance, as it may be harder to specialize when encounters with prey are more variable. Third, if individuals differ in their degree of foraging specialization, then we expect that the success of foraging specialists and generalists will be equal. Specialist hunters should fare better when prey variability is lower, while flexible hunters should fare better when prey variability is higher.

# Squelette de l'intro

- Paragraphe 1 : Importance of among-individual variation in foraging behaviour

- Paragraphe 2 : Factors shaping individual variation in foraging behaviour - the role of experience
  (sources Weimerskirch, 2005, 2007) (explain mechanisms). Explain how it may unravel why foraging specialists are often thought to be more succesful.
  
- Paragraphe 3: (Linking prey variability to experience (woo et al.)) how trophic interactions are probably the main driver of learning and experience

- Paragraphe 4 (système qu'on utilise) (jeux vidéo : paragraphe le + court possible)

- Paragraphe 5 (objectifs et hypotèses)

*Idéé* :
- Est-ce que ça se pourrait que les proies déterminent si les prédateurs se spécialize avec l'expérience ou plutôt deviennent flexible? Dans ce cas, j'utiliserais pas la covariance mais le comportement des proies en effet fixe sur la variance? ou il faudrait que je change les covariances?

*Ideas* : 
- * we now have metrics that enable the quantification of individual specialization (cleasby)*

*Ideas* : integrate the hypotheses of Glaudas et al. ?????


\newpage
# Litterature cited {.unnumbered}

<div id="refs"></div>

